### ISSUE TITLE
error: expected type-specifier fcl

### ISSUE THREAD

**Issue by jdc-pub** [philip-long/ros_collision_checking#4]
After installing `licccd` and `fcl` from source, I am unable to build `fcl_interface` with `colcon`. I get the error shown below. For reference, a demo which shows this example with the `ros:humble` container is available at [cadojo/robot_collision_checking_demo](https://github.com/cadojo/robot_collision_checking_demo).

```
robot_collision_checking on  main 
⬢ [Docker] ❯ colcon build
Starting >>> robot_collision_checking
--- stderr: robot_collision_checking                             
/workspaces/robot_collision_checking/src/robot_collision_checking/src/fcl_interface.cpp: In function ‘robot_collision_checking::FCLCollisionGeometryPtr robot_collision_checking::fcl_interface::createCollisionGeometry(const Octomap&)’:
/workspaces/robot_collision_checking/src/robot_collision_checking/src/fcl_interface.cpp:111:35: error: expected primary-expression before ‘(’ token
  111 |     return FCLCollisionGeometryPtr(new fcl::OcTreed(tree));
      |                                   ^
/workspaces/robot_collision_checking/src/robot_collision_checking/src/fcl_interface.cpp:111:40: error: expected type-specifier
  111 |     return FCLCollisionGeometryPtr(new fcl::OcTreed(tree));
      |                                        ^~~
gmake[2]: *** [CMakeFiles/fcl_interface.dir/build.make:76: CMakeFiles/fcl_interface.dir/src/fcl_interface.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/fcl_interface.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< robot_collision_checking [3.27s, exited with code 2]

Summary: 0 packages finished [3.37s]
  1 package failed: robot_collision_checking
  1 package had stderr output: robot_collision_checking
```

---

This issue is part of a JOSS [review](https://github.com/openjournals/joss-reviews/issues/7473).

**Comment by mazrk7** [comment]
Hi @cadojo, thanks for sharing your repository with the Docker container! I believe this has to do with the order in which Octomap and FCL are installed, where `OcTree` collision geometries are not built if Octomap is not available:
https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/geometry/octree/octree.h#L43

I've updated the `README.md` to warn of this required build order.

You can update your container to install `liboctomap-dev` prior to FCL and see if that allows you to build the package. Let me know if that fixes things and I'll close the issue afterwards. Thanks!

**Comment by jdc-pub** [comment]
This did indeed solve the build error! Thanks for the quick reply & README fix. I'll continue to tick through my review checklist. For reference, [this commit](https://github.com/cadojo/robot_collision_checking_demo/commit/e942a2d3f65974666a9e82bf0c5e293241130dd8) in my demo repository is what solved the issue: `sudo apt install liboctomap-dev` before building FCL.
